#toml

# 表現力レッスン（ヘルプ）
visual_lesson_msg = """
:smile: %nickname%にお稽古をつけていただけるのですね！嬉しいです！
:slightly: どのお題目にしますか？私、精いっぱい頑張りますね！
```
・ヘルプ
　（何ができる）
・チャンネル案内
　（雑談したい、～どこ？～案内して、など）
・朝昼晩のあいさつ
　（おはよう、こんにちは、こんばんは）
・食事のあいさつ
　（いただきます、ごちそうさま）
・出会い、別れのあいさつ
　（いってきます、またね、ただいま）
・褒められたとき
　（かわいい、なでなで、よしよし、いいこいいこ）
・愛情表現をされたとき
　（好きだよ、ぎゅー）
・エミリーと遊ぶ
　（にらめっこ、笑うと負けよ）
　（じゃんけんぽんorあいこでしょ＋✊✌✋のいずれか）
・人探し
　（大和撫子の名前＋どこ、知らない？、見なかった？）
・アカペラ
　（「〇〇〇」＋歌って）
　※詳細は「歌詞orボーカル＋レッスン」を参照してください
・呼称変更
　（「〇〇〇」＋呼んで）
　※ある程度親密になっていないと呼んでくれません
・かくれんぼ
　※ステータスをオフラインにして会話をしてみてください
```"""

# 歌詞レッスン（Sing機能ヘルプ）
vocal_lesson_msg = """
:smile: 歌のお稽古ですね！
:blush: なかなか上手く歌えなくて…よろしければ、%nickname%も一緒に歌ってはもらえませんか？
```
・現在歌えるのは「はなしらべ」の1番のみとなります。
・文章の一番最初か最後に「♪」をつけてください。
・スペースや漢字・ひらがなのゆれはおおよそ大丈夫なはずです。
・1フレーズ歌うと、次の1フレーズを歌ってくれます。歌ったフレーズの分、歌い返してくれます。
・フレーズの区切りは歌詞カード準拠です。途中で区切るとうまく続けることができません。
例）「♪ぽつりぽつり雨音が」→「♪水たまりではしゃげば」
```"""

where_idol_not_found_msg = ":slightly: 申し訳ありません、私はお見かけしていないですね…美咲さんならご存じなのではないでしょうか。"

[testtable]
"てすと" = [
	{ res = "<:emoji1:427396034855960586> てすとです", prob = 1 }
]