#toml

# 歌詞マッチング用
search_lyric_data = [
    "ぽつりぽつり(雨音|あまおと)が",
    "(水|みず)(溜|たまり)ではしゃげば",
    "(咲|さ)いて(消|き)える(波紋|はもん)",
    "まるで(花|はな)の(様|よう)です",
    "(瞬|まばた)きの(隙間|すきま)",
    "(形|かたち)を(変|か)えてく",
    "(儚|はかな)い(物|)もの",
    "(彩|いろど)る(世界|せかい)",
    "(逃|のが)さない(様|よう)に",
    "(心|こころ)(澄|す)まして",
    "ひととき",
    "ひとひらの",
    "(美|うつく)しさに(出会|であ)いたい",
    "(芽吹|めぶ)く(願|ねが)いが",
    "ほら",
    "(私|わたし)を(織|お)り(成|な)してく",
    "そっと(雲|くも)を(解|ほど)いて",
    "(風|かぜ)を(染|そ)める",
    "(光|ひかり)の(指先|ゆびさき)",
    "(導|みちび)かれるまま"
]

# 歌詞レスポンス用
res_lyric_data = [
    "ぽつりぽつり雨音が",
    "水たまりではしゃげば",
    "咲いて消える波紋",
    "まるで花のようです",
    "まばたきの隙間",
    "形を変えてく",
    "儚いもの",
    "彩る世界",
    "逃さないように",
    "心すまして",
    "ひととき",
    "ひとひらの",
    "美しさに出会いたい",
    "芽吹く願いが",
    "ほら",
    "私を織り成してく",
    "そっと雲を解いて",
    "風を染める",
    "光の指先",
    "導かれるまま"
]
