# 【フォーマット】
#
# "コールメッセージ" = [
# 	{ パラメータ=値, パラメータ=値 ... },
# 	{ パラメータ=値, パラメータ=値 ... }
#	...
# ]
#
# コールメッセージ
#	必須
#	何か返答させるときのキーワードになるメッセージ。TOMLの仕様上ダブルクォート""で囲うこと。
#	正規表現を使用可能。
#
# 【パラメータ】
#
#	パラメータは{}の中にカンマ「,」区切りで改行せずに記述すること。
#
#	res="レスポンスメッセージ"
#		必須です。
#		呼びかけに対するエミリーの反応。ダブルクォート「""」で囲うこと。
#		文章に改行を入れたいときは\nと書く。
#		絵文字を使うには、ソースコード側の絵文字テーブルを書き換えてください。
#
#		レスポンスメッセージ中の変数
#		%mention%		コールしたユーザーのメンションに置き換える。文中に入れるときは前後にスペースを入れること。
#		%nickname%		ユーザーが設定した呼称に置き換える。
#		%stutter_nick%	どもった時の呼称に置き換える。1文字目を繰り返す。漢字を変換したりはしない。ex)仕掛け人さま→仕、仕掛け人さま
#		%sleep_nick%	寝ているときの呼称に置き換える。1文字、2文字、3文字以上で若干仕様が異なる。ex)仕掛け人さま→仕……さま
#	
#	prob=数値
#		必須。
#		応答メッセージの確率。全体に対しての比率なので、合計を100にする必要はない。
#		100%のときは適当にprob=1とでもしておく。
#
#	affection=数値
#		オプション
#		親愛度上昇値。デフォルトは1。
#
#	public=(true | false)
#		オプション
#		サーバー上にあるチャンネル内での呼びかけに反応するかどうかを指定する。
#		デフォルトはtrueなので、主に反応させたくないときに使う。
#		
#	private=(true | false)
#		オプション
#		DMでの呼びかけに反応するかどうかを指定する。
#		デフォルトはtrueなので、主に反応させたくないときに使う。
#
#	lock_affection=数値
#		オプション
#		親愛度が数値以上になると抽選から除外する。
#
#	unlock_affection=数値
#		オプション
#		親愛度が数値以上になると抽選対象になる。
#
#	sleep=(true | false)
#		オプション
#		trueであれば寝ている状態のときのみ抽選対象になる。
#		デフォルトの寝言と合わせて抽選が行われるので、確率は大きめに設定しておくとよい。
#		デフォルトはfalse。
#
#	type="スクリプトタイプ"
#		オプション
#		レスポンスメッセージ内にスクリプトを記述することによって、特殊な動作をさせる。
#		デフォルトはplane
#
#		スクリプトタイプ一覧
#		plane	特に何もしない。変数の変換は行われる。
#
#		scroll	レスポンスメッセージに"[ms]"を入れることで、指定時間待ってから次のメッセージが送られる。メッセージは追記される。
#				ただしスクリプトはメッセージの先頭および末尾にあってはならない。
#				例）メッセージ１[1000]メッセージ２[500]メッセージ
#
#	location="(match | unmatch | any)"
#		オプション
#		エミリーの現在位置と発言元のチャンネルの一致不一致で反応するかどうかを指定する
#		ただしDMは指定によらず全て反応する
#		デフォルトはmatch
#		match	チャンネルが一致しているときのみ反応
#		unmatch	チャンネルが一致していないときのみ反応
#		any		チャンネルによらず常に反応
#

#"" = [
#	{ res="", prob=1},
#]

"(にらめっこ|笑うと負けよ)" = [
	{ res = ":daruma: あっぷっぷ！", prob = 1, func="resNiramekko", affection = 2 },
]

"(なでなで|よしよし|いいこいいこ)" = [
	{ res = ":blush: ah...i want more...\n:neutoral: はっ！い、いえっなんでもありませんっ！", prob = 10, affection = 3 },
	{ res = ":blush: あの、もっと…してくださいませんか…？今だけですから…。", prob = 5, affection = 10, public = false },
	{ res = ":blush: %nickname%に触れられると、不思議と心がやわらぐのは何故なんでしょう…。ひょっとして、頭のツボに秘密があるのでしょうか…？", prob = 30, affection = 3 },
	{ res = ":blush: %stutter_nick%…は、恥ずかしいでしゅ…", prob = 60, affection = 3 },
	{ res = ":blush: えへへ…なんだかふわふわした気持ちになります…♪", prob = 30, affection = 3, unlock_affection = 500 },
	{ res = ":smile: では私からも、な〜でな〜で♪\n[2000]…ふふっいかがですか？", prob = 30, affection = 3, type = "scroll"},
	{ res = ":slightly: 仕掛け人さまの手、あたたかくて安心します…。", prob = 30 },
	{ res = ":blush: （そっ、そういうのは二人きりの時にしていただけると…っ！）", prob = 30 },
	{ res = ":sleeping: んん……ん～……（ごろん", prob = 100, affection = 0, sleep=true },
	{ res = ":sleeping: んん……くしゅぐったいでしゅ……", prob = 100, affection = 1, sleep=true, unlock_affection = 200 },
	{ res = ":smile: えへへ……くしゅぐったいでしゅ……♪", prob = 200, affection = 2, sleep=true, unlock_affection = 400 },
	{ res = ":smile: んん～…♪（すりすり", prob = 200, affection = 3, sleep=true, unlock_affection = 600 },
    { res = ":sleeping: ん……%sleep_nick%……", prob = 100, sleep=true },
    { res = ":sleeping: ふふ…%nickname%、お主も悪よのう……", prob = 100, sleep=true }
]

"(かわいい|可愛い)" = [
	{ res = ":smile: ふふっ、ありがとうございます、%nickname%♪", prob = 50, affection = 3},
	{ res = ":blush: そんな、かわいいだなんて…%nickname%に言われると、なんだか照れてしまいます…。", prob = 30, affection = 3 },
	{ res = ":blush: （…えへへっ）", prob = 20, affection = 3, private = false },
	{ res = ":blush: …えへへっ！（ぎゅーっ", prob = 5, affection = 10, public = false },
	{ res = ":desyu: そんな、私なんて……えへへっ", prob = 30 },
	{ res = ":smile: %nickname%も、いつもお茶目でかわいいと思いますよ♪", prob = 30 },
	{ res = ":blush: あの、もっと…[2000]近くで聴かせてくださいませんか？", prob = 30, type="scroll" }
]

"またね" = [
	{ res = ":smile: はい、また遊びにいらしてくださいね♪", prob = 90 },
	{ res = ":blush: もう、行ってしまわれるのですね…少し、寂しいです…。", prob = 30, unlock_affection = 500 },
	{ res = ":blush: あの、…なるべく早く帰ってきてくださいね？", prob = 30 }
]

"こんにちは" = [
	{ res = "funcで処理", prob = 1, func = "resHello" }
]

"「.*」.*歌って" = [
	{ res = "func側で処理", prob = 1, func = "resSingPlease", affection = 3 }
]

"歌って(?!.*る)" = [
	{ res = ":smile: 何がよろしいですか？「」をつけてくださいね。\n:blush: まだあまり多くは歌えませんが…", prob = 1 }
]

"(なに|何)が(でき|出来)る" = [
	{ res = ":slightly: ご挨拶ができます。朝起きたとき、お仕事に行かれるときなどにお声かけくださいね。", prob = 10, location="any" },
	{ res = ":slightly: この茶室にいる人数を答えることができますよ。", prob = 10, location="any" },
	{ res = ":smile: にらめっこで遊ぶことができますよ。実は、にらめっこには自信があるんです！", prob = 10, location="any" },
	{ res = ":smile: %nickname%、じゃんけんをしましょう！\n:blush: それで、もし私が勝ったら…ご褒美をくださいませんか？", prob = 10, location="any" },
	{ res = ":slightly: 他の大和撫子をお探しのときは、私に聞いてみてください。もしかしたら知っているかもしれません。", prob = 10, location="any" },
	{ res = ":blush: お、お褒めいただくと、何かしら反応いたします…。", prob = 10, location="any" },
	{ res = ":blush: %stutter_nick%のお気持ちは理解しているつもりですが、女の子は、時には口に出して言っていただきたいものなのですよ…？", prob = 3, location="any" },
	{ res = ":thinking: あ、頭が、急に…かゆくなってしまいました～…(ﾁﾗｯ\n:blush: ちょうど手がふさがっていて…ど、どうしましょう～(ﾁﾗｯﾁﾗｯ", prob = 10, location="any" },
]

"(ビジュアル|表現力)レッスン" = [
	{ res="プログラム内で上書き", prob=1, location="any"}
]

"(好|す)きだよ" = [
	{ res = ":smile: ふふっ、ありがとうございます、%nickname%♪\n:desyu: （～～～！！）", prob = 30, affection = 5 },
	{ res = ":blush: %stutter_nick%…人前でそのような事を言われると…は、恥ずかしいです…。", prob = 40, affection = 5, private = false},
	{ res = ":smile: はいっ、%nickname%のお気持ちに応えられるような、立派な大和撫子になりますね！", prob = 30, affection = 5 },
	{ res = ":blush: （こしょこしょ…）", prob = 10, func = "resLovecall", affection = 10, private = false },
	{ res = ":smile: 私も%nickname%のことが…大好きですっ！…ふふっ♪", prob = 5, affection = 10, public = false },
	{ res = ":blush: 私も、%nickname%のことが…その………です……。", prob = 10, affection = 5, public = false },
	{ res = ":smile: ありがとうございます、とても嬉しいです♪", prob = 30 },
	{ res = ":slightly: 私も、お慕いしておりますよ…%nickname%…。", prob = 5, affection = 10, public = false },
	{ res = ":blush: そ、そういうは心の準備が出来てからに…！", prob = 10 },
#	{ res = ":smile: ありがとうございます。\n私の気持ちは……言わずとも伝わってますよね？ふふっ♪", prob = 10, }
]

"おはよ" = [
	{ res = ":smile: おはようございます、%nickname%♪", prob = 10 },
	{ res = ":smile: はいっ！今日も元気に参りましょう！", prob = 10 }
]

"こんばん" = [
	{ res = ":slightly: 遅くまでお疲れ様です、%nickname%。無理はなさらないでくださいね？", prob = 1 },
]

"おやす" = [
	{ res = ":slightly: お疲れ様でした。ゆっくりお休みくださいね。", prob = 10 },
	{ res = ":slightly: はい、では夢の中で、また。", prob = 10 }
]

"(眠|ねむ)い" = [
	{ res = ":thinking: 少しお休みになられては…無理をなさらないでくださいね。", prob = 50 },
	{ res = ":thinking: じ、実は、正座の練習をしたいのですが～、どうしてもすぐ足を崩してしまうので～…ええっと…。\n:neutoral: そう！膝に乗せる重石が欲しくて…ですね！\n:blush: その、ちょうど、%nickname%の頭くらいの重さだと、よいのですが………いかがですか？", prob = 10 },
	{ res = ":blush: お膝……お使いになりますか？", prob = 10 },
	{ res = ":slightly: （すっ…）\n:smile: はいっ、いつでも頭を預けてくださいませ♪（ぽんぽんっ）", prob = 30, public = false },
	{ res = ":smile: ふ～っ……ふふっ眠気は覚めましたか？", prob = 30 }
]

"ただいま" = [
	{ res = ":smile: おかえりなさいませ、%nickname%。", prob =  1 },
]

"(エミリー)*.*おかえり(エミリー)*" = [
	{ res = ":smile: はいっ！ただいま、%nickname%♪おでかけ楽しかったです～！", prob = 1, affection = 2 }
]

"(い|行)って(くる|きます)" = [
	{ res = ":smile: お気をつけて。いってらっしゃいませ！", prob = 1, location="any" },
]

"いただきます" = [
	{ res = ":slightly: 自然の恵みに、そして、私たちを日々応援してくださっているごヒイキさま方に感謝して…いただきます。", prob = 10 },
	{ res = ":smile: 健康の為にも、よく噛んで食べましょうね♪", prob = 10 }
]

"ごちそうさま" = [
	{ res = ":smile: お粗末様でした。食後に温かいお茶などいかがですか？雪歩さんに教えていただいたんです。", prob = 1 },
]

"(疲|つか)れた" = [
	{ res = ":neutoral: だ、大丈夫ですか！？私に出来ることは…あっ、肩でもお揉みしましょうか？お茶を入れてきますか？えっと、えっと…！\n:blush: …ほ、抱擁でも…？", prob = 10 },
	{ res = ":thinking: 今日は早めにお休みになられてはいかがでしょう？少し、心配です……。", prob = 10 }
]

"(大丈夫|平気)だよ" = [
	{ res = ":slightly: ご無理はなさらないでくださいね？たまには私を頼ってください。いつも、一番近くで見ていますから…。", prob = 1 }
]

"ぎゅー" = [
	{ res = ":blush: %stutter_nick%！？あ、あの…だ、誰かに見られると…その、か、勘違いをされてしまいます…。えっ、何をって…それは、その…はぅぅ…。", prob = 1, affection = 5 }
]

"(ありがとう|ありがサンキュー)" = [
	{ res=":smile: どういたしまして。いつも%nickname%には支えて頂いてばかりですから…喜んでいただけたなら、嬉しいです♪", prob = 1, affection=3 }
]

"(頑張|がんば)ろう" = [
	{ res = ":smile: はいっ！%nickname%がいてくだされば、百人力…いえ、百万力、ですから！", prob = 70, affection=2 },
	{ res = ":smile: はいっ！\n:slightly: %nickname%…私の背中、お預けしますね。", prob = 30, affection=2 }
]

"(慰|なぐさ)めて" = [
	{ res = "func側で処理", prob = 1, func = "resComfort", location="any" }
]
"(泣|な)きたい" = [
	{ res = "func側で処理", prob = 1, func = "resComfort", location="any" }
]
"しんどい" = [
	{ res = "func側で処理", prob = 1, func = "resComfort", location="any" }
]

"(じゃんけん.*ぽん|じゃんけん.*ぽん|あいこで.*しょ)" = [
	{ res = ":smile: ぽんっ！✊", prob = 20, func = "resPlayRPS", affection = 2 },
	{ res = ":smile: ぽんっ！✌", prob = 20, func = "resPlayRPS", affection = 2 },
	{ res = ":smile: ぽんっ！✋", prob = 20, func = "resPlayRPS", affection = 2 },
	{ res = ":smile: ぽんっ♪✊", prob = 20, func = "resPlayRPS", affection = 2 },
	{ res = ":smile: ぽんっ♪✌", prob = 20, func = "resPlayRPS", affection = 2 },
	{ res = ":smile: ぽんっ♪✋", prob = 20, func = "resPlayRPS", affection = 2 },
]

"エミリー.*「(.*)」.*呼んで" = [
	{ res = "func側で処理", prob = 1, func = "resSetNickName", affection = 1 }
]

"(\d)分.*教えて" = [
	{ res = ":smile: %mention% お時間ですよ～！", prob = 1, func = "resSetTimer", affection = 2 }
]

"(サーバー|茶室).*(何人)" = [
	{ res = "func側で処理", prob = 1, func = "resCountServerMember" }
]

"(どこ.*？|知らない？|見なかった？|見てない？)" = [
	{ res = "func側で処理", prob = 1, func = "resWhereIdol" }
]

"(自己紹介|名刺).*(どこ|案内|したい)" = [
	{ res = ":slightly: 自己紹介や名刺交換をされたいのでしたら、 <#407288754227642369> という帳面がございますので、そちらをお使いください。\n:smile: 茶室が賑わうのを見ると、私も嬉しいです。", prob = 1 }
]

"(雑談|ゲーム).*(どこ|案内|したい)" = [
	{ res = ":slightly: 劇場に関することや、他の事務所について他のみなさまとお話をされたいときは <#419806128373760021> を。\nそれ以外のご自身の趣味や他の遊戯については、 <#407252417386643486> をお使いくださいね。", prob = 1 }
]

"抹茶.*(どこ|案内|したい)" = [
	{ res = ":desyu: Wow! それならぜひ <#415459179524915201> の帳面に書いて、みなさまにも教えてさしあげてください！\n:blush: （後でこっそり私も見に行こっと…♪）", prob = 1 }
]

"郁原.*(どこ|案内|したい)" = [
	{ res = ":smile: 郁原ゆうさまについてのお話でしたら、 <#407283958267641856> の帳面をお使いください。\n:slightly: どのような方か私は詳しくはないのですが…その方のお話を聞いていると、なんだか私のことのように幸せな気持ちになるんです…。", prob = 1 }
]

"ライブ.*(どこ|案内|したい)" = [
	{ res = ":smile: 私たちの公演について、また贈ってくださる花輪についてのお話は <#407270063658369074> の帳面が使われていますよ。\n:slightly: あっ、感想については、公演が終わるまではなるべく <#407284535240425473> をお使いくださいね。\n:smile: みなさまのご期待に応えられるよう、私も頑張りますね！", prob = 1 }
]

"ネタバレ.*(どこ|案内|したい)" = [
	{ res = ":slightly: 公演・放送・遊戯の催しが終了する前に、それらについての感想をお話されるときは <#407284535240425473> の帳面を使い、他のみなさまにご配慮いただきますよう、よろしくお願いしますね。", prob = 1 }
]

"実況.*(どこ|案内|したい)" = [
	{ res = ":slightly: 放送の実況をされるときは  <#407277285071388672> をお使いください。\n:smile: みんなで一緒に見ると、一層楽しいですよね。", prob = 1 }
]

"(茶室|サーバー).*(意見|要望).*(どこ|案内|したい)" = [
	{ res = ":slightly: 茶室の運用についてのご意見・ご要望がありましたら <#431218466461057024> を用意しておりますので、そちらにどうぞ。みんなでより良い茶室を作ってまいりましょうね。", prob = 1 }
]


"役職の一覧を見せて" = [
	{ res = "テストです", prob = 1, func="resShowRoles" }
]

"みんなに(伝えて|お知らせして)" = [
	{ res = "func側で処理", prob = 1, func = "resSetAnnounce" }
]

"お知らせを消して" = [
	{ res = "func側で処理", prob = 1, func = "resDeleteAnnounce" }
]

"お知らせを見せて" = [
	{ res = "func側で処理", prob = 1, func = "resShowAnnounce" }
]

"エミリー.*猫語をインストールして" = [
	{ res="", prob=1, func="resCatLanguage", unlock_affection=200 }
]

"エミリー.*(おいで|こっち)" = [
	{ res="func側で処理", prob=1, func="resMoveChannel", affection=3, location="unmatch" }
]

"(おいで|こっち).*エミリー" = [
	{ res="func側で処理", prob=1, func="resMoveChannel", affection=3, location="unmatch" }
]

"test" = [
	{ res="location match", prob=1, location="match"},
	{ res="location unmatch", prob=1, location="unmatch"},
	{ res="location any", prob=1, location="any"}
]