#toml

"美咲" = [
    { res = ":slightly: あっ、%nickname%。美咲さんも探しておられましたよ。社長さんが大事な話があるそうで…。", prob = 20 }
]

#   "エミリー" = [
#    { res = ":smile: はい、私はずっと%nickname%のおそばにいますよ♪", prob = 20,
#    { res = ":smile: あっ、%nickname%。ちょうどいいところに。お抹茶を点てていたところですので、ご一緒にいかがですか？", prob = 20,
#]

"翼" = [
    { res = "", prob = 0 }
]

"環" = [
    { res = ":slightly: 環さんでしたら、こぶんさんを探して劇場内を走り回っておりましたよ。%nickname%も見かけたら教えてあげてくださいね。", prob = 20 },
    { res = ":smile: あっ、%nickname%。環さんでしたら…ふふっ、先ほど頭に葉っぱを乗せて、泥んこになって帰ってきましたよ。まるで狸さんのようで…。\n:newtoral: ……！%nickname%、私が見た環さんは、はたして本当の環さんなのでしょうか…。", prob = 20 }
]

"未来" = [
    { res = ":smile: 未来さんでしたら、控え室で静香さんに宿題を教わっていましたよ。", prob = 20 }
]

"麗花" = [
    { res = ":slightly: あっ、麗花さんでしたら、屋上へ向かわれましたよ。\n:smile: 「ちょっと空をお散歩してくるねー！」っておっしゃってましたけど…ふふっ麗花さんなら本当に飛べそうですね♪", prob = 20 }
]

"志保" = [
    { res = "", prob = 0 }
]

"ひなた" = [
    { res = "", prob = 0 }
]

"海美" = [
    { res = ":blush: ええと…走ってくる！と言って出て行かれましたよ。\n…随分と前のことですが…。", prob = 20 }
]

"歌織" = [
    { res = ":smile: あっ、%nickname%！先ほど歌織さんと一緒にジュリアさんの弾き語りを聴かせていただいてたんですけどっ、しばらくして歌織さんが立ち上がったと思ったら、洋琴で協奏をし始めて…！\n:desyu: はぁ…今思い出しても耳が幸せです…！", prob = 20 }
]

"美奈子" = [
    { res = "", prob = 0 }
]

"可憐" = [
    { res = "", prob = 0 }
]

"エレナ" = [
    { res = "", prob = 0 }
]

"ジュリア" = [
    { res = ":slightly: あっ、%nickname%。ジュリアさん、これから六弦琴で弾き語りをするそうで、一緒に聴きませんかと歌織さんに誘われたんです。%nickname%もご一緒にいかがですか？", prob = 20 },
    { res = ":slightly: あっ、%nickname%。ジュリアさんは、先ほどまで控え室にいらっしゃいましたよ。\n:desyu: 六弦琴の弾き語りをされていたのですが、反骨精神のときのジュリアさんとはまた違った、柔らかな曲調と歌声が素敵でした…。", prob = 20 },
]

"紬" = [
    { res = "", prob = 0 }
]

"桃子" = [
    { res = "", prob = 0 }
]

"紗代子" = [
    { res = "", prob = 0 }
]

"琴葉" = [
    { res = "", prob = 0 }
]

"朋花" = [
    { res = "", prob = 0 }
]

"まつり" = [
    { res = "", prob = 0 }
]

"恵美" = [
    { res = "", prob = 0 }
]

"風花" = [
    { res = "", prob = 0 }
]

"育" = [
    { res = ":smile: 育さんでしたら、春香さんと調理室へ向かわれましたよ。春香さんにお料理を教わるんだそうです。", prob = 20 },
]

"昴" = [
    { res = "", prob = 0 }
]

"百合子" = [
    { res = ":slightly: 百合子さんでしたら、控え室で本を読んでいらっしゃいましたよ。\n:blush: そろそろ\"戻して\"さしあげたほうがよいかと…。", prob = 20 },
    { res = ":slightly: 百合子さんでしたら、控え室で杏奈さんと電子遊戯をされていましたよ。", prob = 20 },
    { res = ":smile: 百合子さんは、入場口でごヒイキさまから送っていただいた花輪を撮影しに行かれましたよ。それはもう、満面の笑みを浮かべて♪", prob = 20 },
    { res = ":newtoral: 百合子さんでしたら、先日のお芝居の衣装を試着されていると思います。妄想が捗る…とおっしゃっていました…。", prob = 20 },
    { res = ":slightly: 百合子さんでしたら、事務室に行かれましたよ。恐らく、お仕事の予定を確認されるおつもりかと。", prob = 20 },
    { res = ":blush: 先ほど、亜美さんと真美さんと走って外に…。\n:thinking: レイ…えっと、襲撃だー！とおっしゃってましたが…。", prob = 20 },
    { res = ":slightly: …あのご様子だと、恐らく「へんさんしつ」に行かれたのかと。\n:何をする場所なのか私はわからないのですが……百合子さん、そこに向かわれるときは、とても幸せそうなお顔をされるんです。", prob = 5 },
]

"千鶴" = [
]

"茜" = [
    { res = ":blush: ええと…恐らく、あちらの部屋かと…。お人形が溢れてますね…。", prob = 20 },
    { res = ":slightly: 先ほど、麗花さんに連れられてどこかへ向かわれてましたよ。\n:thinking: 撮影で使った宇宙服を持っていたようですが…何に使うのでしょう？", prob = 20 },
]

"星梨花" = [
]

"このみ" = [
    { res = ":slightly: このみさんでしたら、莉緒さんに妖艶な姿勢のお稽古をしてもらっているところを見ましたよ。", prob = 20 },
]

"のり子" = [
    { res = ":blush: あっ、%nickname%。\n:newtoral: どうもあずささんが外出されてから、戻られてないみたいで…%nickname%を探しておられましたよ。心配ですね…。", prob = 20 },
]

"歩" = [
]

"瑞希" = [
]

"亜利沙" = [
]

"美也" = [
]

"静香" = [
]

"杏奈" = [
]

"莉緒" = [
]

"可奈" = [
]

"奈緒" = [
]

"(ロコ|コロちゃん|みちこ)" = [
    { res = ":slightly: ロコさんでしたら、控え室で艶やかな姿勢をとっている莉緒さんの絵を描いておられましたよ。", prob = 20 },
    { res = ":smile: ロコさんでしたら、まつりさんと一緒にいるところを先ほど見かけましたよ。とっても素敵な『お城』を制作していらっしゃるそうです。\n:blush: 私も何かお手伝いできないでしょうか…（うずうず", prob = 20 },
]

"律子" = [
]

"春香" = [
]

"響" = [
    { res = ":smile: 響さんでしたらしばらく前に、環さんと一緒にいぬ美さんのお散歩へ行かれましたよ。", prob = 20 },
    { res = ":slightly: 先ほどレッスン室で、歩さんと舞踊勝負をされているのを見かけましたよ。\n:smile: お二人ともすごかったです！", prob = 20 },
]

"真" = [
]

"千早" = [
]

"貴音" = [
    { res = ":thinking: すみません、貴音さまは先ほど廊下ですれ違っただけなので、どちらにいらっしゃるかまでは…。\n:smile: あっ、でも、その時に天体観測のお誘いを受けたんです。もしかしたら、屋上にいらっしゃるかもしれません。", prob = 20 },
]

"やよい" = [
]

"雪歩" = [
]

"亜美" = [
]

"真美" = [
]

"美希" = [
]

"あずさ" = [
]

"伊織" = [
    { res = ":slightly: 伊織さまでしたら、衣装室におられましたよ。\n:smile: 営業笑顔の練習、だとか。", prob = 20 },
]
