title="Come on a Tea Party!"

artist="星梨花"

    lyrics=""":smile: 星梨花さんの曲ですね！私も可愛らしくて好きです♪[3000]では…[3000]
:desyu: ♪ふぁっと甘い[1200]アールグレイ[1200]
:singing: 爽やか[1200]ミントティー[1500]
ショートケーキ[1200]キスチョコ[1000]みんなお好きかな[2600]
色とりどりのお花を[2500]飾りたい[1100]
もう早く[1000]早く[800]明日になっちゃえ[3000]
:desyu: ……[2000]はぁ～、なんだかお腹が空いてきました♪[2000]%nickname%、お茶にしませんか？"""

humming=""":desyu: ふん[800]ふふふん[1200]ふふ[800]ふふふん[1200]ふん[2500]
ふふん[800]ふふふん[1200]ふふ[2000]ふふふふん♪"""