title="(Eternal Harmony|エターナルハーモニー|永遠の交響曲|エタハモ)"

artist=""

lyrics=""":slightly: すぅっ……[3000]
:singing: ARE YOU READY？[930]
LOVE! & SOUL![1150]届けたいよ[1300]
キミの声聞かせて[1800]I FEEL IT![950]
ドキドキが[1400]ハジけてくよ[1100]
ココロに響いてる[2600]
この胸の奥[3500]途切れない永遠に[2600]
エターナル[1600]ハーモニー[1400]
もっと[500]FEEL WITH ME![3000]
:smile: 一緒に頑張りましょうね！"""