title="(Sentimental\s*Venus|感傷的.*乙女|センチメンタル.*ヴィーナス)"

artist="(伊織|エミリー|瑞希|莉緒)"

lyrics=""":smile: はいっ！[1500]では、幕を開きますよ…[2000]フェードイン！[1200]
:singing: Sentimental Venus[1300]
ため息から[1400]こぼれたPrism[1400]受け取るよ[1300]
偶然とか[1300]信じないわ[1500]意味ありげな[1300]シチュエイションに[2400]
踊るココロは[2600]正直なの[2300]キミに恋してる[3800]迎えにいこう[3000]
:smile: ……[2000]楽しんでいただけましたか？[2000]%nickname%っ♪"""

humming=""":smile: ♪ふん～ふふふふふん[3000]ふん～ふふふふふん[3000]
ふん～ふふふふふん[3000]ふふん～ふふんふん"""
