title="To(\.\.\.|…)"

artist="このみ"

lyrics=""":blush: こ、[1000]このみさんの曲ですか…！？[2500]
私のような若輩者が、[1500]あのような大人の楽曲を歌ってもよいのでしょうか…。[3500]
でも…[1500]%nickname%がそうおっしゃるなら……[3000]い、いきます！[2500]
:singing: ねぇ[660]甘えて[910]みてもいい？[2700]
この恋が[1300]本当だと[1200]伝えてみたいの[2000]
そのひと時は[2000]ふざけたりは無しだよ[3300]
素顔のままでいたい[2260]
ねぇ[530]弱さを[800]見せてもいい？[2700]
この恋が本物と[2500]感じて欲しいから[2000]
その一瞬は[2000]嘘ついてもいいから[3300]
優しく[1500]ギュッと抱きしめて[5000]
:blush: ……[1500]い、[1000]いかがでしたでしょうか…？[3000]……[3000]私の気持ち、[1500]伝わりましたか？"""