title="だってあなたはプリンセス"

artist="Charlotte Charlotte"

lyrics=""":singing: [1000]フワフワリ[1800]
髪を揺らして[2900]お茶にしましょう[3800]
ときめきパフュームに乗せて[4800]いくの[1200]
キラキラリ[1800]
まるでステキな[2900]ドールみたいに[3800]
もっともっと輝ける[3300]
だって[1800]あなたはプリンセス[4500]
:smile: ……[2000]催し物で疲れたときは、[1000]またお呼びくださいね♪"""
