title="ハッピ.*エフェクト"

artist="美也"

lyrics=""":smile: 美也さんの曲ですね！[2500]「なかなか渋いところを突きますなぁ～」[3000]…ふふっ、[1500]似てましたか？[1500]では！[3000]
:singing: ♪ひらひら飛んでった[1900]ちょうちょの[1900]
羽ばたきだって[1700]お天気予報[2100]
きれいな瞬間[1700]つかまえた！[2000]晴れますよ[3500]
ちいさな風に[1900]気付いた[1900]笑顔がいっぱいに[1900]広がって[1900]
あしたもぜったいに[1900]HAPPY DAY！[1900]いい日です～[3000]
:smile: ……[2000]ん～、[2000]お散歩に行きたくなってきました！"""

humming=""":desyu: ♪茶柱が立ってました～[3000]今日の私も幸せです～[3000]
みんなにわけてあげたなら～[3000]きっとみんなも幸せです～[5000]
:blush: （……お抹茶だと、茶柱立たないなぁ…残念…）"""