title="ランニング・ハイッ"

artist="キャンサー"

lyrics=""":smile: はいっ！[1000]では、合いの手をしっかり、お願いしますね！[5000]
:singing: ♪みんな[1500]WINNERになりたいの！[3800]
Let's 競争！[1500]
キャンディーなカラーの[1500]ランニングシューズ、[1000]CUTE！[700]
しっかり地球を蹴っ飛ばし（ :smile: はいっ）[2500]
太陽に照らされた[2000]TRACK to GOAL、[1000]DASH！[700]
一秒を一瞬で置き去ってく（ :smile: はいっ）[2800]
思いっきり[1800]走っていくってね[2000]気分爽快[1500]
遠慮せずにヒートアップ！[2500]Woo YEAH！[3000]
:smile: ……[2000]はぁ～！[2000]日光律動の曲はやはり楽しいです～！"""