title="君だけの欠片"

artist="エミリー"

lyrics=""":blush: わかりました。えっと…では、お隣、失礼しますね。[5000]
:singing: ♪あざやかに彩ってく[5000]涙も[2000]
迷いも[1300]君だけの欠片[3000]
だから隣で[3000]泣いてもいいんだよ[2500]
手と手[2500]ぎゅっと[2500]繋いで[3000]
:smile: ……[2000]いかがでしたか？"""

humming=""":smile: ♪la la...[3000]la la la...[5000]la la la la...[3000]la la..."""