title="微笑み日和"

artist="エミリー"

lyrics=""":smile: では、%nickname%もご一緒に♪[5000]
:singing: ♪清く正しく美しく[4000]祈りを心に[3000]
奏でる[2000]想いを届けます[4000]
曇りなき空の向こう[4000]迷わず行きましょう[3300]
微笑む日々と[3000]一緒に[1000]あこがれに咲く[3000]明日へと[3000]
:desyu: ……[2000]あぁ、%nickname%と一緒にこの曲を歌えるだなんて…！"""

humming="""ふんふふんふん～[3000]ふふん～ふふふん～[3000]
そばーにー[1200]もっといたいっ♪[4000]……[1000]:desyu:"""
