title="瑠璃色金魚と花菖蒲"

artist="紬"

lyrics=""":blush: %stutter_nick%…もしかして、密かに練習していたの、見ていらしたのですか…？[5000]
:newtoral: で、では…いきます…！[5000]
:singing: ♪外の世界は[2000]ねえ[1000]なんて眩しい[1800]
嘘だとしても[1700]罪深すぎたの[2200]
眩暈がしても[1900]心地いいのは[1700]
もう[2800]求めてるから[3000]
:blush: ……[2000]ふぅ…[1000]歌ってみると、紬さんの凄さがわかります…。"""